### ISSUE TITLE
Game refuses to connect.

### ISSUE THREAD

**Issue by wafflethings** [klukule/CatapultServer.Proxy#2]
I have used OpenSSL to generate a .pfx cert, and it does not error in VS and while running but the game does not connect.

**Comment by wafflethings** [comment]
For whatever reason, there is an error when I Alt-F4 the game so I assume it's connecting, but something's stopping it from working.

**Comment by klukule** [comment]
Hey,

This is really old project of mine, which was made long before EAC was introduced. And there was no season 2 yet. So the devs might have changed something, and since I personally don't play FallGuys anymore I won't be updating and/or fixing this lib.

Sorry.

**Comment by wafflethings** [comment]
I see.

**Comment by wafflethings** [comment]
Sorry for reopening, but this seems to be an issue with something I've done since it doesn't work on S1 either. Is it possible you could give me your SSL cert pfx if it isn't a security risk and you still have the files? Not sure how this stuff works.

**Comment by klukule** [comment]
No problem... I just checked my local files and I sadly don't have the certificates anymore. Sorry I can't help you more.
